---
- name: Install Apache
  apt:
    name: apache2
    state: present
  ignore_errors: true
  when: action == "install"

- name: Restart apache2 service
  ansible.builtin.service:
    name: apache2
    state: restarted
  register: apache_restarted
  ignore_errors: true
  when: action == 'restart'

- name: Include Jira role to comment on issue
  include_role:
    name: Jira
  vars:
    action: comment
    apache_restarted: apache_restarted
    issue_key: "{{ issue_key }}"
  when: apache_restarted.changed

- name: Include Jira role to resolve issue
  include_role:
    name: Jira
  vars:
    action: resolve
    jira_issue: "{{ issue_key }}"
  when: apache_restarted.changed
