---
- name: Include JIRA credentials
  include_vars:
    file: jira_credentials.yml
    name: jira_creds
  no_log: false

- name: Create an issue
  community.general.jira:
    uri: '{{ jira_creds.jira_server }}'
    username: '{{ jira_creds.jira_user }}'
    password: '{{ jira_creds.jira_pass }}'
    project: GP
    operation: create
    summary: Example Issue
    description: Created using Ansible
    issuetype: Task
  args:
    fields:
      customfield_10079: {"value": "A"}
  register: new_jira_issue
  when: jira_issue is not defined and (action is not defined or action == 'create')

- name: Set JIRA issue key
  set_fact:
    issue_key: "{{ new_jira_issue.meta.key if jira_issue is not defined else jira_issue }}"
  when: new_jira_issue.meta is defined or jira_issue is defined

- name: Comment on JIRA issue
  community.general.jira:
    uri: '{{ jira_creds.jira_server }}'
    username: '{{ jira_creds.jira_user }}'
    password: '{{ jira_creds.jira_pass }}'
    issue: '{{ issue_key }}'
    operation: comment
    comment: '{{ comment }}'
  register: commented_on_jira
  when: action == 'comment' 

- name: install apache2
  include_role:
    name: restart
  vars:
    action: install
  register: install_apache2
  when: issue_key is defined

- name: Include restart role to restart service
  include_role:
    name: restart
  vars:
    action: restart
  register: apache_restarted

- name: Comment on JIRA issue
  community.general.jira:
    uri: '{{ jira_creds.jira_server }}'
    username: '{{ jira_creds.jira_user }}'
    password: '{{ jira_creds.jira_pass }}'
    issue: '{{ issue_key }}'
    operation: comment
    comment: apache restarted
  register: commented_on_jira
  when: action == 'comment' and apache_restarted is defined

- name: Resolve the issue
  community.general.jira:
    uri: '{{ jira_creds.jira_server }}'
    username: '{{ jira_creds.jira_user }}'
    password: '{{ jira_creds.jira_pass }}'
    issue: '{{ issue_key }}'
    operation: transition
    status: Done
    fields:
      resolution:
        name: Done
      description: I am done! This is the last description I will ever give you.
  when: action == 'resolve'
