- name: Include JIRA credentials
  include_vars:
    file: jira_credentials.yml
    name: jira_creds
  no_log: false

- name: Create an issue
  community.general.jira:
    uri: '{{ jira_creds.jira_server }}'
    username: '{{ jira_creds.jira_user }}'
    password: '{{ jira_creds.jira_pass }}'
    project: GP
    operation: create
    summary: Example Issue
    description: Created using Ansible
    issuetype: Task
  args:
    fields:
        customfield_10079: {"value": "A"}
  register: new_jira_issue
  when: jira_issue is not defined


- name: Set jira_issue fact to the newly created issue key
  set_fact:
    jira_issue: "{{ new_jira_issue.issue }}"
  when: jira_issue is not defined



- name: Comment on JIRA issue
  community.general.jira:
    uri: "{{ jira_creds.jira_server }}"
    username: "{{ jira_creds.jira_user }}"
    password: "{{ jira_creds.jira_pass }}"
    issue: "{{ jira_issue }}"
    operation: comment
  when: apache_restarted is defined and apache_restarted.changed
  register: commented_on_jira

- name: Resolve the issue
  community.general.jira:
    uri: "{{ jira_creds.jira_server }}"
    username: "{{ jira_creds.jira_user }}"
    password: "{{ jira_creds.jira_pass }}"
    issue: "{{ jira_issue }}"
    operation: transition
    status: Done
    fields:
      resolution:
        name: Done
      description: I am done! This is the last description I will ever give you.
    when: commented_on_jira is defined