---
- name: Include JIRA credentials
  include_vars:
    file: jira_credentials.yml
    name: jira_creds
  no_log: false

- name: create issue
  roles:
    - role: Jira
  when: jira_issue is not defined

- name: restart apache
  hosts: db
  remote_user: ubuntu
  become: true
  roles:
    - role: restart_apache
  when: new_jira_issue is defined

- name: comment on issue
  roles:
    - role: Jira
  comment: apache restarted
  when: apache_restarted is defined and apache_restarted.changed
