---
- name: Include JIRA credentials and create issue
  hosts: localhost
  gather_facts: false
  roles:
    - role: JIRA
      comment: "Starting Restart process"
  when: jira_issue is defined

- name: Restart apache2 on db servers
  hosts: db
  remote_user: ubuntu
  become: true
  tasks:
    - name: restart apache2 service
      ansible.builtin.include_role:
        name: restart
