---
- name: Restart apache2 on db servers
  hosts: db 
  remote_user: ubuntu
  become: true
  roles:
    - Jira
    - restart_apache
    
- name: Set apache_restarted fact
  set_fact:
    apache_restarted: "{{ apache_restart_result.results[1] }}"
  when: apache_restart_result is defined
  

   

