---
- name: restart apache
  hosts: db
  remote_user: ubuntu
  become: true
  roles:
    - role: restart_apache
  when: new_jira_issue is defined

- name: comment on issue
  roles:
    - role: Jira
  comment: apache restarted
  when: apache_restarted is defined and apache_restarted.changed
