---
- name: Include JIRA credentials and create issue
  hosts: localhost
  gather_facts: false
  roles:
    - role: Jira
      vars:
        action: comment
        comment: "Starting Restart process"

- name: Include JIRA credentials and create issue
  hosts: localhost
  gather_facts: false
  roles:
    - role: Jira
      vars:
        action: comment
        comment: "Starting Restart process"

- name: Include JIRA credentials and create issue
  hosts: localhost
  gather_facts: false
  roles:
    - role: Jira
      vars:
        action: comment
        comment: "Starting Restart process"
      
