---
- name: Include JIRA credentials and create issue
  hosts: localhost
  gather_facts: false
  tasks:
    - name: create issue
      ansible.builtin.include_role:
        name: jira

- name: Restart apache2 on db servers
  hosts: db
  remote_user: ubuntu
  become: true
  tasks:
    - name: restart apache2 service
      ansible.builtin.include_role:
        name: restart
