---
- name: Restart apache2 on db servers
  hosts: db 
  remote_user: ubuntu
  become: true

  tasks:
    - name: ensure apache2 Install
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: restart apache2 service
      service:
        name: apache2
        state: restarted 