---
- name: Include JIRA credentials and restartStart Comment
  hosts: localhost
  gather_facts: false
  roles:
    - role: jira2
      vars:
        action: restartStart
        comment: "Starting Restart process"

- name: Restart apache2 on app servers
  hosts: app
  remote_user: ubuntu
  become: true
  roles:
    - role: restart2
      vars:
        action: restartApache2

- name: Include JIRA credentials and restartComplete
  hosts: localhost
  gather_facts: false
  roles:
    - role: jira2
      vars:
        action: restartComplete
        comment: "Restart has been completed"
      
