---
- name: Include JIRA credentials and restartStart Comment
  hosts: localhost
  gather_facts: false
  roles:
    - role: jira2
      vars:
        action: restartStart
        comment: "Starting Restart process"

- name: Include JIRA credentials and restartComplete
  hosts: localhost
  gather_facts: false
  roles:
    - role: jira2
      vars:
        action: resolve
        comment: "Restart has been completed"
      
