---
- name: Prompt for assignee if new issue created
  hosts: localhost
  vars_prompt:
    - name: assign_user
      prompt: "Enter the username of the assignee for the new issue"
      private: false
  register: assign_user
  vars: 
    jira_assignee: "{{ assign_user }}"
  tasks:
    - name: Debug assign_user variable
      debug:
        var: assign_user

    - name: set fact for new issue
      set_fact:
        new_issue_created: true
      when: jira_issue is not defined 

- name: Include JIRA credentials and restartStart Comment
  hosts: localhost
  gather_facts: false
  roles:
    - role: jira2
      vars:
        action: restartStart
        comment: "Starting Restart process"
        jira_assignee: "{{ assign_user }}"

- name: Restart apache2 on app servers
  hosts: app
  remote_user: ubuntu
  become: true
  roles:
    - role: restart2
      vars:
        action: restartApache2

- name: Include JIRA credentials and restartComplete
  hosts: localhost
  gather_facts: false
  roles:
    - role: jira2
      vars:
        action: restartComplte
        comment: "Restart has been completed"
      
