--- 
- hosts: all
  become: true


  tasks:
  - name: debug ec2 instances
    ansible.builtin.debug:
      var: ansible_facts

  - name: shutdown ec2 instances
    command: /sbin/shutdown -t now
    when: 
     ansible_facts['os_family'] == "Centos"