---
- name: Include JIRA credentials
  include_vars:
    file: jira_credentials.yml
    name: jira_creds
  no_log: false

- name: Create an issue if jira_issue is not defined
  community.general.jira:
    uri: '{{ jira_creds.jira_server }}'
    username: '{{ jira_creds.jira_user }}'
    password: '{{ jira_creds.jira_pass }}'
    project: GP
    operation: create
    summary: Example Issue
    description: Created using Ansible
    issuetype: Task
  args:
    fields:
      customfield_10079: {"value": "A"}
  register: new_jira_issue
  when: jira_issue is not defined

- name: Set JIRA issue key to new or existing issue
  set_fact:
    issue_key: "{{ jira_issue if jira_issue is defined else new_jira_issue.meta.key }}"

 
- name: Assign the issue to the user running the playbook or specified user
  community.general.jira:
    uri: '{{ jira_creds.jira_server }}'
    username: '{{ jira_creds.jira_user }}'
    password: '{{ jira_creds.jira_pass }}'
    issue: '{{ issue_key }}'
    operation: update
    fields:
      assignee: 
        name: '{{ jira_assignee }}'
  when: issue_key is defined and jira_issue is not defined

- name: Comment on JIRA issue
  community.general.jira:
    uri: '{{ jira_creds.jira_server }}'
    username: '{{ jira_creds.jira_user }}'
    password: '{{ jira_creds.jira_pass }}'
    issue: '{{ issue_key }}'
    operation: comment
    comment: '{{ comment }}'
  register: commented_on_jira
  when: action == 'restartStart' or action == 'restartComplete'

- name: Resolve the issue
  community.general.jira:
    uri: '{{ jira_creds.jira_server }}'
    username: '{{ jira_creds.jira_user }}'
    password: '{{ jira_creds.jira_pass }}'
    issue: '{{ issue_key }}'
    operation: transition
    status: Done
    fields:
      resolution:
        name: Done
      description: I am done! This is the last description I will ever give you.
  when: action == 'resolve'
